# Generated by Django 4.2.3 on 2023-12-31 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_task_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='Project',
        ),
    ]
